export const surah = [
  {
    number: 1,
    name: 'Al-Fatiha',
    translation: 'The Opening',
    total_verses: 7,
    url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume01/(0003)fateha/surahe%20fateha.mp3',
  },
  {
    number: 2,
    name: 'Al-Baqarah',
    translation: 'The Cow',
    total_verses: 286,
    url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume01/(0004)albaqara/intro(albaqara).mp3',
  },
  {
    number: 3,
    name: 'Aali Imran',
    translation: 'The Family of Imran',
    total_verses: 200,
  },
  {
    number: 4,
    name: 'An-Nisa',
    translation: 'The Women',
    total_verses: 176,
  },
  {
    number: 5,
    name: "Al-Ma'idah",
    translation: 'The Table Spread',
    total_verses: 120,
  },
  {
    number: 6,
    name: "Al-An'am",
    translation: 'The Cattle',
    total_verses: 165,
  },
  {
    number: 7,
    name: "Al-A'raf",
    translation: 'The Heights',
    total_verses: 206,
  },
  {
    number: 8,
    name: 'Al-Anfal',
    translation: 'The Spoils of War',
    total_verses: 75,
  },
  {
    number: 9,
    name: 'At-Tawbah',
    translation: 'The Repentance',
    total_verses: 129,
  },
  {
    number: 10,
    name: 'Yunus',
    translation: 'Jonah',
    total_verses: 109,
  },
  {
    number: 11,
    name: 'Hud',
    translation: 'Hud',
    total_verses: 123,
  },
  {
    number: 12,
    name: 'Yusuf',
    translation: 'Joseph',
    total_verses: 111,
  },
  {
    number: 13,
    name: "Ar-Ra'd",
    translation: 'The Thunder',
    total_verses: 43,
  },
  {
    number: 14,
    name: 'Ibrahim',
    translation: 'Abraham',
    total_verses: 52,
  },
  {
    number: 15,
    name: 'Al-Hijr',
    translation: 'The Rocky Tract',
    total_verses: 99,
  },
  {
    number: 16,
    name: 'An-Nahl',
    translation: 'The Bee',
    total_verses: 128,
  },
  {
    number: 17,
    name: 'Al-Isra',
    translation: 'The Night Journey',
    total_verses: 111,
  },
  {
    number: 18,
    name: 'Al-Kahf',
    translation: 'The Cave',
    total_verses: 110,
  },
  {
    number: 19,
    name: 'Maryam',
    translation: 'Mary',
    total_verses: 98,
  },
  {
    number: 20,
    name: 'Ta-Ha',
    translation: 'Ta-Ha',
    total_verses: 135,
  },
  {
    number: 21,
    name: 'Al-Anbiya',
    translation: 'The Prophets',
    total_verses: 112,
  },
  {
    number: 22,
    name: 'Al-Hajj',
    translation: 'The Pilgrimage',
    total_verses: 78,
  },
  {
    number: 23,
    name: "Al-Mu'minun",
    translation: 'The Believers',
    total_verses: 118,
  },
  {
    number: 24,
    name: 'An-Nur',
    translation: 'The Light',
    total_verses: 64,
  },
  {
    number: 25,
    name: 'Al-Furqan',
    translation: 'The Criterion',
    total_verses: 77,
  },
  {
    number: 26,
    name: "Ash-Shu'ara",
    translation: 'The Poets',
    total_verses: 227,
  },
  {
    number: 27,
    name: 'An-Naml',
    translation: 'The Ant',
    total_verses: 93,
  },
  {
    number: 28,
    name: 'Al-Qasas',
    translation: 'The Stories',
    total_verses: 88,
  },
  {
    number: 29,
    name: 'Al-Ankabut',
    translation: 'The Spider',
    total_verses: 69,
  },
  {
    number: 30,
    name: 'Ar-Rum',
    translation: 'The Romans',
    total_verses: 60,
  },
  {
    number: 31,
    name: 'Luqman',
    translation: 'Luqman',
    total_verses: 34,
  },
  {
    number: 32,
    name: 'As-Sajda',
    translation: 'The Prostration',
    total_verses: 30,
  },
  {
    number: 33,
    name: 'Al-Ahzab',
    translation: 'The Confederates',
    total_verses: 73,
  },
  {
    number: 34,
    name: 'Saba',
    translation: 'Sheba',
    total_verses: 54,
  },
  {
    number: 35,
    name: 'Fatir',
    translation: 'The Originator',
    total_verses: 45,
  },
  {
    number: 36,
    name: 'Ya-Sin',
    translation: 'Ya-Sin',
    total_verses: 83,
  },
  {
    number: 37,
    name: 'As-Saffat',
    translation: 'Those who set the Ranks',
    total_verses: 182,
  },
  {
    number: 38,
    name: 'Sad',
    translation: 'The Letter Sad',
    total_verses: 88,
  },
  {
    number: 39,
    name: 'Az-Zumar',
    translation: 'The Groups',
    total_verses: 75,
  },
  {
    number: 40,
    name: 'Ghafir',
    translation: 'The Forgiver',
    total_verses: 85,
  },
  {
    number: 41,
    name: 'Fussilat',
    translation: 'Explained in Detail',
    total_verses: 54,
  },
  {
    number: 42,
    name: 'Ash-Shura',
    translation: 'The Consultation',
    total_verses: 53,
  },
  {
    number: 43,
    name: 'Az-Zukhruf',
    translation: 'The Gold Adornments',
    total_verses: 89,
  },
  {
    number: 44,
    name: 'Ad-Dukhan',
    translation: 'The Smoke',
    total_verses: 59,
  },
  {
    number: 45,
    name: 'Al-Jathiya',
    translation: 'The Crouching',
    total_verses: 37,
  },
  {
    number: 46,
    name: 'Al-Ahqaf',
    translation: 'The Wind-Curved Sandhills',
    total_verses: 35,
  },
  {
    number: 47,
    name: 'Muhammad',
    translation: 'Muhammad',
    total_verses: 38,
  },
  {
    number: 48,
    name: 'Al-Fath',
    translation: 'The Victory',
    total_verses: 29,
  },
  {
    number: 49,
    name: 'Al-Hujurat',
    translation: 'The Rooms',
    total_verses: 18,
  },
  {
    number: 50,
    name: 'Qaf',
    translation: 'The Letter Qaf',
    total_verses: 45,
  },
  {
    number: 51,
    name: 'Adh-Dhariyat',
    translation: 'The Winnowing Winds',
    total_verses: 60,
  },
  {
    number: 52,

    name: 'At-Tur',
    translation: 'The Mount',
    total_verses: 49,
  },
  {
    number: 53,
    name: 'An-Najm',
    translation: 'The Star',
    total_verses: 62,
  },
  {
    number: 54,
    name: 'Al-Qamar',
    translation: 'The Moon',
    total_verses: 55,
  },
  {
    number: 55,
    name: 'Ar-Rahman',
    translation: 'The Beneficent',
    total_verses: 78,
  },
  {
    number: 56,
    name: 'Al-Waqia',
    translation: 'The Inevitable',
    total_verses: 96,
  },
  {
    number: 57,
    name: 'Al-Hadid',
    translation: 'The Iron',
    total_verses: 29,
  },
  {
    number: 58,
    name: 'Al-Mujadila',
    translation: 'The Pleading Woman',
    total_verses: 22,
  },
  {
    number: 59,
    name: 'Al-Hashr',
    translation: 'The Exile',
    total_verses: 24,
  },
  {
    number: 60,
    name: 'Al-Mumtahina',
    translation: 'She that is to be Examined',
    total_verses: 13,
  },
  {
    number: 61,
    name: 'As-Saff',
    translation: 'The Ranks',
    total_verses: 14,
  },
  {
    number: 62,
    name: 'Al-Jumua',
    translation: 'The Congregation',
    total_verses: 11,
  },
  {
    number: 63,
    name: 'Al-Munafiqun',
    translation: 'The Hypocrites',
    total_verses: 11,
  },
  {
    number: 64,
    name: 'At-Taghabun',
    translation: 'The Mutual Disillusion',
    total_verses: 18,
  },
  {
    number: 65,
    name: 'At-Talaq',
    translation: 'The Divorce',
    total_verses: 12,
  },
  {
    number: 66,
    name: 'At-Tahrim',
    translation: 'The Prohibition',
    total_verses: 12,
  },
  {
    number: 67,
    name: 'Al-Mulk',
    translation: 'The Sovereignty',
    total_verses: 30,
  },
  {
    number: 68,
    name: 'Al-Qalam',
    translation: 'The Pen',
    total_verses: 52,
  },
  {
    number: 69,
    name: 'Al-Haqqah',
    translation: 'The Reality',
    total_verses: 52,
  },
  {
    number: 70,
    name: 'Al-Maarij',
    translation: 'The Ascending Stairways',
    total_verses: 44,
  },
  {
    number: 71,
    name: 'Nuh',
    translation: 'Noah',
    total_verses: 28,
  },
  {
    number: 72,
    name: 'Al-Jinn',
    translation: 'The Jinn',
    total_verses: 28,
  },
  {
    number: 73,
    name: 'Al-Muzzammil',
    translation: 'The Enshrouded One',
    total_verses: 20,
  },
  {
    number: 74,
    name: 'Al-Muddathir',
    translation: 'The Cloaked One',
    total_verses: 56,
  },
  {
    number: 75,
    name: 'Al-Qiyama',
    translation: 'The Resurrection',
    total_verses: 40,
  },
  {
    number: 76,
    name: 'Al-Insan',
    translation: 'Man',
    total_verses: 31,
  },
  {
    number: 77,
    name: 'Al-Mursalat',
    translation: 'The Emissaries',
    total_verses: 50,
  },
  {
    number: 78,
    name: 'An-Naba',
    translation: 'The Tidings',
    total_verses: 40,
  },
  {
    number: 79,
    name: 'An-Naziat',
    translation: 'Those who drag forth',
    total_verses: 46,
  },
  {
    number: 80,
    name: 'Abasa',
    translation: 'He frowned',
    total_verses: 42,
  },
  {
    number: 81,
    name: 'At-Takwir',
    translation: 'The Overthrowing',
    total_verses: 29,
  },
  {
    number: 82,
    name: 'Al-Infitar',
    translation: 'The Cleaving',
    total_verses: 19,
  },
  {
    number: 83,
    name: 'Al-Mutaffifin',
    translation: 'Defrauding',
    total_verses: 36,
  },
  {
    number: 84,
    name: 'Al-Inshiqaq',
    translation: 'The Splitting Open',
    total_verses: 25,
  },
  {
    number: 85,
    name: 'Al-Buruj',
    translation: 'The Mansions of the Stars',
    total_verses: 22,
  },
  {
    number: 86,
    name: 'At-Tariq',
    translation: 'The Morning Star',
    total_verses: 17,
  },
  {
    number: 87,
    name: 'Al-Ala',
    translation: 'The Most High',
    total_verses: 19,
  },
  {
    number: 88,
    name: 'Al-Ghashiya',
    translation: 'The Overwhelming',
    total_verses: 26,
  },
  {
    number: 89,
    name: 'Al-Fajr',
    translation: 'The Dawn',
    total_verses: 30,
  },
  {
    number: 90,
    name: 'Al-Balad',
    translation: 'The City',
    total_verses: 20,
  },
  {
    number: 91,
    name: 'Ash-Shams',
    translation: 'The Sun',
    total_verses: 15,
  },
  {
    number: 92,
    name: 'Al-Lail',
    translation: 'The Night',
    total_verses: 21,
  },
  {
    number: 93,
    name: 'Ad-Duha',
    translation: 'The Morning Hours',
    total_verses: 11,
  },
  {
    number: 94,
    name: 'Ash-Sharh',
    translation: 'The Relief',
    total_verses: 8,
  },
  {
    number: 95,
    name: 'At-Tin',
    translation: 'The Fig',
    total_verses: 8,
  },
  {
    number: 96,
    name: 'Al-Alaq',
    translation: 'The Clot',
    total_verses: 19,
  },
  {
    number: 97,
    name: 'Al-Qadr',
    translation: 'The Power',
    total_verses: 5,
  },
  {
    number: 98,
    name: 'Al-Bayyina',
    translation: 'The Clear Proof',
    total_verses: 8,
  },
  {
    number: 99,
    name: 'Az-Zalzalah',
    translation: 'The Earthquake',
    total_verses: 8,
  },
  {
    number: 100,
    name: 'Al-Adiyat',
    translation: 'The Courser',
    total_verses: 11,
  },
  {
    number: 101,
    name: 'Al-Qaria',
    translation: 'The Calamity',
    total_verses: 11,
  },
  {
    number: 102,
    name: 'At-Takathur',
    translation: 'Rivalry in worldly increase',
    total_verses: 8,
  },
  {
    number: 103,
    name: 'Al-Asr',
    translation: 'The Declining Day',
    total_verses: 3,
  },
  {
    number: 104,
    name: 'Al-Humaza',
    translation: 'The Traducer',
    total_verses: 9,
  },
  {
    number: 105,
    name: 'Al-Fil',
    translation: 'The Elephant',
    total_verses: 5,
  },
  {
    number: 106,
    name: 'Quraish',
    translation: 'Quraish',
    total_verses: 4,
  },
  {
    number: 107,
    name: 'Al-Maun',
    translation: 'The Small Kindnesses',
    total_verses: 7,
  },
  {
    number: 108,
    name: 'Al-Kawthar',
    translation: 'The Abundance',
    total_verses: 3,
  },
  {
    number: 109,
    name: 'Al-Kafirun',
    translation: 'The Disbelievers',
    total_verses: 6,
  },
  {
    number: 110,
    name: 'An-Nasr',
    translation: 'The Divine Support',
    total_verses: 3,
  },
  {
    number: 111,
    name: 'Al-Masad',
    translation: 'The Palm Fiber',
    total_verses: 5,
  },
  {
    number: 112,
    name: 'Al-Ikhlas',
    translation: 'The Sincerity',
    total_verses: 4,
  },
  {
    number: 113,
    name: 'Al-Falaq',
    translation: 'The Daybreak',
    total_verses: 5,
  },
  {
    number: 114,
    name: 'An-Nas',
    translation: 'Mankind',
    total_verses: 6,
  },
];
