export const Volume = [
  {
    vol_id: 1,
    surah_data: [
      {
        surah_id: 1,
        surah_name: 'Deebacha',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume01/(0001)deebacha/deebacha.mp3',
      },
      {
        surah_id: 2,
        surah_name: 'Muqadma',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume01/(0002)muqadma/muqadma.mp3',
      },
      {
        surah_id: 3,
        surah_name: 'Fateha',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume01/(0003)fateha/fateha(intro).mp3',
      },
      {
        surah_id: 4,
        surah_name: 'Al-Baqrah',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume01/(0004)albaqara/rukoo01baqara.mp3',
      },
      {
        surah_id: 5,
        surah_name: 'Aal-e-imran',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume01/(0005)aaleimran/intro(aaleimran).mp3',
      },
      {
        surah_id: 6,
        surah_name: 'An-Nisa',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume01/(0006)annisa/intro(an-nisa).mp3',
      },
      {
        surah_id: 7,
        surah_name: 'Al-Maida',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume01/(0007)almaida/intro(al-maida).mp3',
      },
      {
        surah_id: 8,
        surah_name: 'Al-Anaam',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume01/(0008)alanaam/rukoo01alanaam.mp3',
      },
    ],
  },
  {
    vol_id: 2,
    surah_data: [
      {
        surah_id: 9,
        surah_name: 'Al-Aaraf',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(007)alaaraf/intro(al-aaraf).mp3',
      },
      {
        surah_id: 10,
        surah_name: 'Al-Anfaal',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(008)alanfal/intro(al-anfal).mp3',
      },
      {
        surah_id: 11,
        surah_name: 'At-Touba',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(009)at-tauba/intro(at-tauba).mp3',
      },
      {
        surah_id: 12,
        surah_name: 'Younas',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(010)younus/intro(younus).mp3',
      },
      {
        surah_id: 13,
        surah_name: 'Hood',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(011)huud/intro(huud).mp3',
      },
      {
        surah_id: 14,
        surah_name: 'Yousuf',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(012)yousuf/intro(yousuf).mp3',
      },
      {
        surah_id: 15,
        surah_name: 'Ar-Raad',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(013)ar-raad/intro(ar-raad).mp3',
      },
      {
        surah_id: 16,
        surah_name: 'Ibrahim',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(014)ibrahim/intro(ibrahim).mp3',
      },
      {
        surah_id: 17,
        surah_name: 'Al-Hijr',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(015)al-hijr/intro(al-hijr).mp3',
      },
      {
        surah_id: 18,
        surah_name: 'Al-Nahal',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(016)an-nahal/intro(an-nahal).mp3',
      },
      {
        surah_id: 19,
        surah_name: 'Bani-Israil',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume02/(017)bani-israil/intro(bani-israil).mp3',
      },
    ],
  },
  {
    vol_id: 3,
    surah_data: [
      {
        surah_id: 20,
        surah_name: 'Al-Kahaf',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/al-kahaf(intro).mp3',
      },
      {
        surah_id: 21,
        surah_name: 'Maryam',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(019)ma ryam/maryam(intro).mp3',
      },
      {
        surah_id: 22,
        surah_name: 'Taha',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(020)taha/(intro)taha.mp3',
      },
      {
        surah_id: 23,
        surah_name: 'Al-Anbiya',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(021)al-anbia/al-anbia(intro).mp3',
      },
      {
        surah_id: 24,
        surah_name: 'Al-Hajj',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/al-hajj(intro).mp3',
      },
      {
        surah_id: 25,
        surah_name: 'Al-Mominoon',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(023)al-mominoon/al-mominoon(intro).mp3',
      },
      {
        surah_id: 26,
        surah_name: 'An-Noor',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/an-noor(intro).mp3',
      },
      {
        surah_id: 27,
        surah_name: 'Al-Furqan',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(025)al-furqan/al-furqan(intro).mp3',
      },
      {
        surah_id: 28,
        surah_name: 'Ash-Shoara',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/ash-shoara(intro).mp3',
      },
      {
        surah_id: 29,
        surah_name: 'An-Namal',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(027)an-namal/an-namal(intro).mp3',
      },
      {
        surah_id: 30,
        surah_name: 'Al-Qasas',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/al-qasas(intro).mp3',
      },
      {
        surah_id: 31,
        surah_name: 'Al-Ankaboot',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(029)al-ankaboot/al-ankaboot(intro).mp3',
      },
      {
        surah_id: 32,
        surah_name: 'Al-Room',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(030)ar-room/ar-room(intro).mp3',
      },
    ],
  },
  {
    vol_id: 4,
    surah_data: [
      {
        surah_id: 33,
        surah_name: 'Luqman',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(31)luqman/luqman(intro).mp3',
      },
      {
        surah_id: 34,
        surah_name: 'As-Sajda',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(32)as-sijda/as-sijda(intro).mp3',
      },
      {
        surah_id: 35,
        surah_name: 'Al-Ahzaab',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(33)al-ahzab/al-ahzab(intro).mp3',
      },
      {
        surah_id: 36,
        surah_name: 'Saba',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(34)saba/saba(intro).mp3',
      },
      {
        surah_id: 37,
        surah_name: 'Fatir',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(35)fatir/fatir(intro).mp3',
      },
      {
        surah_id: 38,
        surah_name: 'Yaseen',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(36)yaaseen/(intro)yaaseen.mp3',
      },
      {
        surah_id: 39,
        surah_name: 'As-Saaffat',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(37)as-saaffat/as-saaffat(intro).mp3',
      },
      {
        surah_id: 40,
        surah_name: 'Suad',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(38)suad/intro(suad).mp3',
      },
      {
        surah_id: 41,
        surah_name: 'Az-Zumar',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(39)az-zumar/az-zumar(intro).mp3',
      },
      {
        surah_id: 42,
        surah_name: 'Al-Momin',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(40)al-momin/al-momin(intro).mp3',
      },
      {
        surah_id: 43,
        surah_name: 'Ha-mim Sajda',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(41)h.m.as-sijda/hameemas-sijda(intro).mp3',
      },
      {
        surah_id: 44,
        surah_name: 'Ash-Shoora',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(42)ash-shoora/ash-shoora(intro).mp3',
      },
      {
        surah_id: 45,
        surah_name: 'Az-Zukhruf',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(43)az-zukhraf/az-zukhruf(intro).mp3',
      },
      {
        surah_id: 46,
        surah_name: 'Ad-Dukhan',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(44)ad-dukhan/ad-dukhan(intro).mp3',
      },
      {
        surah_id: 47,
        surah_name: 'Al-Jasiya',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(45)al-jasia/al-jasiya(intro).mp3',
      },
      {
        surah_id: 48,
        surah_name: 'Al-Ahqaf',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume04/(46)al-ahqaf/al-ahqaf(intro).mp3',
      },
    ],
  },
  {
    vol_id: 5,
    surah_data: [
      {
        surah_id: 49,
        surah_name: 'Mohammad',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 50,
        surah_name: 'Al-Fatah',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 51,
        surah_name: 'Al-Hujurat',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 52,
        surah_name: 'Qaaf',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 53,
        surah_name: 'Az-Zariat',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 54,
        surah_name: 'At-Toor',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 55,
        surah_name: 'An-Najm',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 56,
        surah_name: 'Al-Qamar',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 57,
        surah_name: 'Ar-Rahman',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 58,
        surah_name: 'Al-Waqiah',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 59,
        surah_name: 'Al-Hadeed',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 60,
        surah_name: 'Al-Mujadla',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 61,
        surah_name: 'Al-Hashr',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 62,
        surah_name: 'Al-Mumtahina',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 63,
        surah_name: 'As-Saff',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 64,
        surah_name: 'Al-Jumah',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 65,
        surah_name: 'Al-Munafiqoon',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 66,
        surah_name: 'At-Taghabun',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
      {
        surah_id: 67,
        surah_name: 'At-Talaq',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume05/(47)mohammad/(intro)mohammad.mp3',
      },
    ],
  },
  {
    vol_id: 6,
    surah_data: [
      {
        surah_id: 68,
        surah_name: 'At-Tehreem',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 69,
        surah_name: 'Al-Mulk',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 70,
        surah_name: 'Al-Qalam',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 71,
        surah_name: 'Al-Haqqa',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 72,
        surah_name: "Al-Ma'arij",
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 73,
        surah_name: 'Nooh',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 74,
        surah_name: 'Al-Jin',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 75,
        surah_name: 'Al-Muzzammil',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 76,
        surah_name: 'Al-Muddassir',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 77,
        surah_name: 'Al-Qiyamah',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 78,
        surah_name: 'Ad-Dahr',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 79,
        surah_name: 'Al-Mursalat',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 80,
        surah_name: 'An-Naba',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 81,
        surah_name: 'An-Nazayaat',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 82,
        surah_name: 'Abas',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 83,
        surah_name: 'At-Takweer',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 84,
        surah_name: 'Al-Infitar',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 85,
        surah_name: 'Al-Mutaffifeen',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 86,
        surah_name: 'Al-Inshiqaq',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 87,
        surah_name: 'Al-Burooj',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 88,
        surah_name: 'At-Tariq',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 89,
        surah_name: 'Al-Aala',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 90,
        surah_name: 'Al-Ghashiya',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 91,
        surah_name: 'Al-Fajr',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 92,
        surah_name: 'Al-Balad',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 93,
        surah_name: 'Ash-Shams',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 94,
        surah_name: 'Al-Lail',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 95,
        surah_name: 'Az-Zuha',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 96,
        surah_name: 'Al-Inshirah',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 97,
        surah_name: 'At-Teen',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 98,
        surah_name: 'Al-Alaq',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 99,
        surah_name: 'Al-Qadr',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 100,
        surah_name: 'Al-Bayyena',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 101,
        surah_name: 'Az-Zilzal',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 102,
        surah_name: 'Al-Aadiyat',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 103,
        surah_name: 'Al-Qaariya',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 104,
        surah_name: 'At-Takasur',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 105,
        surah_name: 'Al-Asr',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 106,
        surah_name: 'Al-Humaza',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 107,
        surah_name: 'Al-Feel',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 108,
        surah_name: 'Quraish',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 109,
        surah_name: 'Al-Maoon',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 110,
        surah_name: 'Al-Kausar',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 111,
        surah_name: 'Al-Kafiroon',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 112,
        surah_name: 'An-Nasr',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 113,
        surah_name: 'Al-Lahab',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 114,
        surah_name: 'Al-Ikhlas',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 115,
        surah_name: 'Al-Falaq',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
      {
        surah_id: 116,
        surah_name: 'An-Naas',
        live_path: '',
        download_path: null,
        download_flag: null,
        url: 'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume06/(066)at-tehreem/at-tehreem(intro).mp3',
      },
    ],
  },
];
